examen/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),
   	url(r'^',include('inspecciones.urls', namespace='inspecciones')),

]

inspecciones/urls.py
from django.conf.urls import url, include
from inspecciones.views import ListaCentros, NuevoCentro, EditarCentro, EliminarCentro, NuevaInspeccion
from . import views
urlpatterns = [
   	


   	url(r'centros/$', ListaCentros.as_view(), name = 'listacentros'),
	url(r'centros/nuevo/$', NuevoCentro.as_view(), name = 'nuevocentro'),
	url(r'centro/editar/(?P<id>[0-9]+)/$', EditarCentro.as_view(), name = 'editarcentro'),
	url(r'centro/eliminar/$', EliminarCentro.as_view(), name = 'eliminarcentro'),
	url(r'vehiculos/$', views.lista_vehiculos, name='listavehiculos'),
	url(r'vehiculos/nuevo/$', views.nuevo_vehiculo, name = 'nuevovehiculo'),
	url(r'vehiculos/editar/(?P<id>[0-9]+)/$', views.editar_vehiculo, name = 'editarvehiculo'),
	url(r'vehiculos/eliminar/$', views.eliminar_vehiculo, name = 'eliminarvehiculo'),
	url(r'inspeccion/nuevo/$', NuevaInspeccion.as_view(), name = 'nuevainspeccion'),
	url('^$',views.index, name= 'index'),
   	url(r'registration/', include('django.contrib.auth.urls')),
	
	

]

inspecciones/models.py
from __future__ import unicode_literals

from django.db import models


class Centro(models.Model):
	nombre = models.CharField(max_length=100)
	telefono = models.IntegerField()

	def __str__(self):
		return self.nombre


class Vehiculo(models.Model):
	nombre = models.CharField(max_length=100)
	modelo = models.CharField(max_length=100)


	def __str__(self):
		return self.nombre


class Inspeccion(models.Model):
	fecha = models.CharField(max_length=100)
	Centro = models.ForeignKey(Centro , on_delete = models.CASCADE)
	Vehiculo = models.ForeignKey(Vehiculo , on_delete = models.CASCADE)

inspecciones/forms.py
from django.forms import ModelForm
from inspecciones.models import Centro, Vehiculo, Inspeccion

class CentroForm(ModelForm):
	class Meta:
		model = Centro
		exclude = ()


class VehiculoForm(ModelForm):
	class Meta:
		model = Vehiculo
		exclude = ()

class InspeccionForm(ModelForm):
	class Meta:
		model = Inspeccion
		exclude = ()

inspecciones/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.views import redirect_to_login
from django.views import View
from inspecciones.models import Centro, Vehiculo, Inspeccion
from inspecciones.forms import CentroForm, VehiculoForm, InspeccionForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum

# Create your views here.


class ListaCentros(View):
	template_name = 'inspecciones/lista_centros.html'

	def get(self, request, *args, **kwargs):
		centros = Centro.objects.all()
		return render(request, self.template_name, { 'centros' : centros })


class NuevoCentro(View):
	template_name = 'inspecciones/editar_centro.html'
	form_class = CentroForm

	def get(self, request, *args, **kwargs):
		form = self.form_class()
		return render(request, self.template_name, { 'form' : form })

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)

		if form.is_valid():
			form.save()
			return redirect(reverse('inspecciones:listacentros'))

		return render(request, self.template_name, { 'form' : form })

	def dispatch(self, *args, **kwargs):
		if self.request.user.is_staff:
			return super(NuevoCentro, self).dispatch(*args, **kwargs)
		else:
			return redirect_to_login(reverse('inspecciones:nuevocentro'))




class EditarCentro(View):
	template_name = 'inspecciones/editar_centro.html'
	form_class = CentroForm

	def get(self, request, *args, **kwargs):
		c_id = kwargs['id']
		c = get_object_or_404(Centro, pk = c_id)
		if not c:
			return redirect(reverse('inspecciones:listacentros'))

		form = self.form_class(instance = c)
		return render(request, self.template_name, { 'form' : form })

	def post(self, request, *args, **kwargs):
		c_id = kwargs['id']
		c = get_object_or_404(Centro, pk = c_id)
		if not c:
			return redirect(reverse('inspecciones:listacentros'))
		form = self.form_class(request.POST, instance = c)

		if form.is_valid():
			form.save()
			return redirect(reverse('inspecciones:listacentros'))

		return render(request, self.template_name, { 'form' : form })

	def dispatch(self, *args, **kwargs):
		if self.request.user.is_staff:
			return super(EditarCentro, self).dispatch(*args, **kwargs)
		else:
			return redirect_to_login(reverse('inspecciones:editarcentro', kwargs = { 'id' : kwargs['id'] }))





class EliminarCentro(View):

	def get(self, request, *args, **kwargs):
		return redirect(reverse('inspecciones:listacentros'))

	def post(self, request, *args, **kwargs):
		c_id = request.POST.get('id')
		c = get_object_or_404(Centro, pk = c_id)
		c.delete()
		return redirect(reverse('inspecciones:listacentros'))

	def dispatch(self, *args, **kwargs):
		if self.request.user.is_staff:
			return super(EliminarCentro, self).dispatch(*args, **kwargs)
		else:
			return redirect_to_login(reverse('inspecciones:listacentros'))






def lista_vehiculos(request):
	template_name = 'inspecciones/lista_vehiculos.html'

	if request.method == 'GET':
		
		vehiculos = Vehiculo.objects.all()

		return render(request, template_name, { 'vehiculos' : vehiculos })



def nuevo_vehiculo(request):
	template_name = 'inspecciones/editar_vehiculo.html'
	form_class = VehiculoForm

	if not request.user.is_staff:
		return redirect_to_login(reverse('inspecciones:nuevovehiculo', kwargs = { 'idcir' : idcir }))

	cir = get_object_or_404(Centro)

	if request.method == 'POST':
		form = form_class(request.POST)

		if form.is_valid():
			form.save()
			return redirect(reverse('inspecciones:listavehiculos'))
	else:
		form = form_class(initial = { 'centro' : cir })
	return render(request, template_name, { 'form' : form })






def editar_vehiculo(request, id):
	template_name = 'inspecciones/editar_vehiculo.html'
	form_class = VehiculoForm

	if not request.user.is_staff:
		return redirect_to_login(reverse('inspecciones:editarvehiculo', kwargs = { 'id' : id }))

	vehiculo = get_object_or_404(Vehiculo, pk = id)
	if not vehiculo:
		return redirect(reverse('inspecciones:listavehiculos'))

	if request.method == 'POST':
		form = form_class(request.POST, instance = vehiculo)

		if form.is_valid():
			form.save()
			return redirect(reverse('inspecciones:listavehiculos'))
	else:
		form = form_class(instance = vehiculo)
	return render(request, template_name, { 'form' : form })





def eliminar_vehiculo(request):
	idvehiculo = request.POST.get('id')
	vehiculo = get_object_or_404(Vehiculo, pk = idvehiculo)


	if not request.user.is_staff:
		return redirect_to_login(reverse('inspecciones:listavehiculos'))

	if request.method == 'POST':
		vehiculo.delete()
		
	return redirect(reverse('inspecciones:listavehiculos'))




class NuevaInspeccion(View):
	template_name = 'inspecciones/nueva_inspeccion.html'
	form_class = InspeccionForm

	def get(self, request, *args, **kwargs):
		form = self.form_class()
		return render(request, self.template_name, { 'form' : form })

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)

		if form.is_valid():
			form.save()
			return redirect(reverse('inspecciones:listacentros'))

		return render(request, self.template_name, { 'form' : form })

	def dispatch(self, *args, **kwargs):
		if self.request.user.is_staff:
			return super(NuevaInspeccion, self).dispatch(*args, **kwargs)
		else:
			return redirect_to_login(reverse('inspecciones:nuevainspeccion'))





def index(request):
	template_name = 'inspecciones/index.html'
	
	return render(request, template_name)

inspecciones/templates/inspecciones/editar_centro.html
{% extends "base.html" %}

{% block title %}Editar centro{% endblock title %}

{% block content %}
<h3>Editar centro</h3>
<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
			    {{form.as_p}}
				<p><input type='submit' value='Guardar'></p>
</form>
{% endblock content %}

inspecciones/templates/inspecciones/editar_vehiculo.html
{% extends "base.html" %}

{% block title %}Editar vehiculo{% endblock title %}

{% block content %}
<h3>Editar vehiculo</h3>
<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
			    {{form.as_p}}
				<p><input type='submit' value='Guardar'></p>
</form>
{% endblock content %}

inspecciones/templates/inspecciones/index.html
{%extends 'base.html'%}
{%block title %}Pagina principal{%endblock%}

{%block content %}<h3>Bienvenido</h3>{%endblock%}

inspecciones/templates/inspecciones/lista_centros.html
{% extends "base.html" %}

{% block title %}Centros{% endblock title %}

{% block content %}
<h3>Listado de centros</h3>
{% if centros %}
	<ul>
	{% for c in centros %}
		<li><a href="{% url 'inspecciones:listacentros'%}">{{ c.nombre }}</a>
		{% if request.user.is_staff %}
		<small><a href="{% url 'inspecciones:editarcentro' c.id %}">Editar</a></small>
		<form style="display:inline" action="{% url 'inspecciones:eliminarcentro' %}" method="POST">
			{% csrf_token %}
			<input type="hidden" value="{{ c.id }}" name="id">
			<button onclick="return confirm('Desea eliminar este centro?');" type="submit">Eliminar</button>
		</form>
		{% endif %}
		</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No existe ningun centro.</p>
{% endif %}
{% if request.user.is_staff %}
	<small><a href="{% url 'inspecciones:nuevocentro' %}">Añadir centro</a></small>
{% endif %}
{% endblock content %}

inspecciones/templates/inspecciones/lista_vehiculos.html
{% extends "base.html" %}

{% block title %}Vehiculos{% endblock title %}

{% block content %}
<h3>Lista de vehiculos</h3>
{% if vehiculos %}
	<ul>
	{% for c in vehiculos %}
		<li><a href="{% url 'inspecciones:listavehiculos'%}">{{ c.nombre }}</a>
		{% if request.user.is_staff %}
		<small><a href="{% url 'inspecciones:editarvehiculo' c.id %}">Editar</a></small>
		<form style="display:inline" action="{% url 'inspecciones:eliminarvehiculo' %}" method="POST">
			{% csrf_token %}
			<input type="hidden" value="{{ c.id }}" name="id">
			<button onclick="return confirm('Desea eliminar este vehiculo?');" type="submit">Eliminar</button>
		</form>
		{% endif %}
		</li>
	{% endfor %}
	</ul>
{% else %}
	<p>No existe ningun vehiculo.</p>
{% endif %}
{% if request.user.is_staff %}
	<small><a href="{% url 'inspecciones:nuevovehiculo' %}">Añadir vehiculo</a></small>
{% endif %}
{% endblock content %}

inspecciones/templates/inspecciones/nueva_inspeccion.html
{% extends "base.html" %}

{% block title %}Nueva Inspeccion{% endblock title %}

{% block content %}
<h3>Nueva Inspeccion</h3>
<form id='form' method='post' enctype='multipart/form-data' action=''>{% csrf_token %}
			    {{form.as_p}}
				<p><input type='submit' value='Guardar'></p>
</form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Inspecciones{% endblock %}</title>
</head>
<body>

<div class="container">
<ul>
	<li><a href="{%url 'inspecciones:listacentros'%}">Lista de centros</a></li>

	<li><a href="{%url 'inspecciones:listavehiculos'%}">Lista de vehiculos</a></li>

	<li><a href="{%url 'inspecciones:nuevainspeccion'%}">Nueva inspeccion</a></li>



	{%if user.is_anonymous%}

	<li><a href="{%url 'inspecciones:login'%}">Login</a></li>

	{%else%}

	<li>Bienvenido {{user.username}}</li>

	<li><a href="{%url 'inspecciones:logout'%}?next=/">Logout</a></li>

	{%endif%}
</ul>
	{% block content %}{% endblock content %}
</div>
</body>
</html>